#### promethus异常关闭

如果promethus异常关闭， oom以后， docker升级，导致关闭。 启动的时候日志出现下面报错:

```
level=error ts=2019-01-24T10:02:47.793695453Z caller=main.go:597 err="Opening storage failed invalid block sequence: block time ranges overlap: [mint: 1548230400000, maxt: 1548237600000, range: 2h0m0s, blocks: 2]
.....
level=info ts=2019-01-24T10:02:47.793932946Z caller=main.go:599 msg="See you next time!"
```

过多无效块导致tsds无法启动，导致不断重新启动。需要人工干预才可以。需要通过tsdb扫描程序把无效block删除:

下载tsdb扫描工具:
```
$wget https://github.com/prometheus/prometheus/files/2148149/tsdbScan.tar.gz
```

扫描命令:
```
$./tsdb scan -h prometheus-db/
```
